### PR TITLE
Fix minor but noticeable issues

### PR DESCRIPTION
**Pull request by DJDavid98**
These issues *(among other CSS-related problems, which I may or may not do a PR for later)* were causing incorrect behaviour on my site. I made these fixes for myself, but when I saw there's a GitHub for this plugin I decided to make a PR with them.

Fixes:

 1. Background image URLs would not be changed if the URL contained parenthesis
 2. When closing, the removeClass function was using a character group incorrectly to check for strings of characters, changed to regular grouping
 3. Add a new line at the end of file - does no harm and git won't complain that there isn't one

I've never used Grunt so I don't know how to compile this, but that should be easy enough should you wish to use this.

### CODE REVIEW

**Comment by terrymun** [comment]
Thanks for the PR. Can you issue the PR with only change №. 2 and 3 implemented? Change № 1 will not be implemented because image URLs have to be escaped accordingly based on RFC 3986–see #112 and #155 on why Fluidbox discourages using non-escaped resource address.

**Comment by terrymun** [comment]
Thanks for the PR. Can you issue the PR with only change №. 2 and 3 implemented? Change № 1 will not be implemented because image URLs have to be escaped accordingly based on RFC 3986–see #112 and #155 on why Fluidbox discourages using non-escaped resource address.

**Comment by DJDavid98** [comment]
Removed the URL escaping, however I do suggest some sort of `console.warn` in the future that the URL is malformed instead of silently failing to display it. Something like this:

    if (url.indexOf(' ') !== -1 || /(\(|\))/g.test(url))
      console.warn('The link '+url+' is malformed and my cause Fluidbox to work incorrectly, please escape the URL etc.');

This should be sufficient, since those seem to be the 2 most common issues.

I'll compile the files and do another commit in a bit.

**Comment by terrymun** [comment]
After doing some further research, it seems like even though web browsers should parse `()[]` characters correctly, jQuery is not. Using `escapeURI` or `escapeURIComponent` will *not* escape these characters, resulting in a possible violation.

I would reverse my original decision and allow regex-based replacement of these characters.

**Comment by DJDavid98** [comment]
`node-sass` is taking ages to install, I'm not sure I can commit the compiled code this evening, if at all.

**Comment by terrymun** [comment]
I can also make the changes on my hand and credit you for it, but I wouldn't be able to create and merge a PR on your behalf. Only if you're okay with that. 

No need to rush this fix, so don't get too worried about it.

**Comment by DJDavid98** [comment]
Assuming I did everything right, the code should be minified properly now

**Comment by terrymun** [comment]
Can you [squash/collapse multiple commits into one](http://stackoverflow.com/questions/2563632/how-can-i-merge-two-commits-into-one)? This is to keep the history clean: here's a guide :)

**Comment by DJDavid98** [comment]
Done.

**Comment by terrymun** [comment]
Thanks for the PR ;)

**Comment by SeinopSys** [comment]
@terrymun Sorry for "reviving" this issue but I wasn't sure how best to contact you. I've since changed my name on GitHub and just noticed my old name (DJDavid98) is still listed in the repository's README file. Is there a chance you could update it?

**Pull request merged**
