### PR TITLE
Refactored repository

### PR DESCRIPTION
**Pull request by maxee**
# Changes
- Moved all demo related files into the new *demo/* directory (except index.html)
- Moved all plugin development related files into the new *src/* directory
- Moved all end-user-related files to the new *dist/js* and *dist/css* directories
- Added gulp.js for easier building (See usage below)
- Removed duplicate license file

# Gulp.js usage
I added the following gulp tasks

Note: The output directories for all tasks are *dist/js* and *dist/css*.

- ```gulp``` runs the default task and generates all js and css files. Afterwards it listens for changes in the *src/* folder and updates the files in *dist/* automatically.
- ```gulp``` only watches for changes but does not initially create js and css files.
- ```gulp js``` generates all js files
- ```gulp css``` generates all css files

### CODE REVIEW

**Comment by terrymun** [comment]
I'm sorry that I have to turn down this PR, because the pull request cannot be merged automatically and that I don't see the purpose behind refactoring the repo—I'm curious, what's the purpose of refactoring it?

**Comment by maxee** [comment]
The merge conflicts would have to be resolved by you, this isn't neccessarily a problem. 

A few of my thoughts why the repo needs a refactoring were the following:
- Demo page sources and plugin sources are mingled at the moment
- There is no real workflow for a developer. I mean, one would need to setup a build environment locally to compile for example the CSS (Directly editing the CSS files is not possible unless one edits the SCSS file accordingly). Another option in this case would be to convert the SCSS via some online service and paste it back. This process is really annoying and time-wasting.

**Comment by terrymun** [comment]
Thanks for the effort in reorganizing. I promise to keep this in view, but I really don't have the time to manually resolve conflicts (and still new to the whole concept of PRs).

**Comment by terrymun** [comment]
As Fluidbox codebase is going to be overhauled, I will pre-emptively close this PR.

**Pull request closed without merging**
