### PR TITLE
Add option for immediate expansion

### PR DESCRIPTION
**Pull request by benwilhelm**
Currently, fluidbox waits for the high-res image to load before expanding.
If you're linking to very large images, this leads to a laggy UI and may
confuse the user into thinking that the link is broken. This adds an option
$.fluidbox({immedate:true}) which will trigger the lightbox load immediately
on click and begin loading the high-res image in the background. When the
high-res has loaded, the low-res is replaced. This commit also adds a utility
class 'fluidbox-loading' and an empty 'fluidbox-status' div on the ghost object
to allow the user to style it with their own UI cues.

### CODE REVIEW

**Comment by joshuapinter** [comment]
Thanks @benwilhelm (and/or @bwilhelm-nni) for adding this immediate expansion feature - just what I was looking for. 

Did you add the necessary changes to the README file in your PR as well?

**Comment by terrymun** [comment]
Thanks for the PR, Ben! I haven't got time to look at the changes and test then, and this will probably have to wait till March. I am also wondering if I should implement a loading indicator, but at the cost of complicating the minimalistic appeal of Fluidbox.

I'll keep in touch with you soon.

**Comment by benwilhelm** [comment]
Thanks Terry. Didn't mean to rush you. This PR includes an empty div called `.fluidbox-status`, and applies the `.fluidbox-loading` class to `.fluidbox-ghost` while the high-res image is loading. If you want to keep the minimalist appeal, you can leave the specifics of loading indicator implementation to the user. Eg.

    .fluidbox-status {
        display: none;
    }

    .fluidbox-loading .fluidbox-status {
        display: block;
        background: url('loading.gif') center center no-repeat;
        width: 20px;
        height: 20px;
        position: absolute;
        top: 0;
        left: 0;
     }

**Comment by joshuapinter** [comment]
Hey guys. I forked @benwilhelm's excellent "immediate" branch and was able to add a very clean and simple **all-CSS** loader that turned out quite well.

Thought I would share the result here in case there is any interest in incorporating it as an option into the library. Again, it's all CSS so no additional images, just a simple `loader: true` option to be passed in.

Here's the result:

Fluidbox with immediate option and loader

_Here's the [original file][1], which is much smoother._

  [1]: https://dl.dropboxusercontent.com/u/26378081/Fluidbox%20with%20immediate%20and%20loader.mp4

**Comment by terrymun** [comment]
This feature is temporarily put on hold. After some testing I find there is a few issues that I am currently unable to address when setting immediate to true:

- Small images being excessively blown up
- Does not work with linked images whose aspect ratio differs from that of thumbnail, resulting in stretches images when the target image is finally loaded

**Pull request merged**
